apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygrpc
spec:
  selector:
    matchLabels:
      app: mygrpc
  template:
    metadata:
      labels:
        app: mygrpc
    spec:
      containers:
      - name: mygrpc
        image: gcr.io/jasondel-test-project/mygrpc:v1
        env:
        - name: LOG_LEVEL
          value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: mygrpc-service
spec:
  type: LoadBalancer
  selector:
    app: mygrpc
  ports:
  - name: http
    port: 80
    targetPort: 80
